name: Code Quality
on:
  workflow_call:
jobs:
  validate-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Run code analysis
        run: dotnet analyze

      - name: Run code formatting
        run: dotnet format

      - name: Run code security
        run: dotnet security

