name: Dependency Scan
on:
  workflow_call:

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Specify your desired .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: List vulnerable libraries
        run: dotnet list package --vulnerable --include-transitive