name: Docker Lint
on:
  workflow_call:

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: MinimalApi/Dockerfile