name: Secrets Scan
on:
  workflow_call:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # gitHub actions manages it
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}